### ISSUE TITLE
Possible typo 

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/displaying-has-many-through-rails#14]
"use" should be "us" in "Calling comment.user returns for **use** the User object associated with that comment. We can then call any method that our user responds to, such as username." Located in the paragraph directly preceding "adding posts to our users" section

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

Thanks for contributing 💙
