### ISSUE TITLE
Completed but not updating

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/displaying-has-many-through-rails#15]
I completed the readme but it is not showing that I have completed it.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
