### ISSUE TITLE
Missing Tests

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/displaying-has-many-through-rails#4]
Tests can't be run, to move on to the next lab.

**Comment by AnnJohn** [comment]
hi @onyoo, this is a codealong readme without tests, the lab right after this one is test driven.

**Comment by onyoo** [comment]
Hey @AnnJohn! Ok, I understand. Learn.co may need updating so it doesn't require students to run tests before proceeding. 

<img width="1209" alt="screen shot 2016-01-21 at 5 21 53 pm" src="https://cloud.githubusercontent.com/assets/14326883/12486598/a3daa1ca-c063-11e5-8b94-18467af9440c.png">

**Comment by onyoo** [comment]
Sorry I wasn't clear the first time!

**Comment by AnnJohn** [comment]
ahhh thanks for reporting this! looks like a technical issue and our product team will look into it. thanks again!!

**Comment by AnnJohn** [comment]
Updated this on our end. Thank you again!
