### ISSUE TITLE
No Tests To Run

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/displaying-has-many-through-rails#5]
This lesson has no tests to run but the lesson requires it to be 100% complete.

**Comment by AnnJohn** [comment]
Hi @Lukeghenco sorry about that. This should just be a reading, and we updated it on Learn. Thanks!

**Comment by Lukeghenco** [comment]
Thanks, I just made a test for mine, so that it would pass.

**Comment by AnnJohn** [comment]
Hey @Lukeghenco, could you make a PR with your tests if you have time? We'll see if we can add it to this readme and change it to a proper lab. 

Thanks!

**Comment by Lukeghenco** [comment]
It was sort of a cheap test that just added a post and checked for that post.
If I have some time today. I can make it a real test and put up a pull request

**Comment by AnnJohn** [comment]
No worries if that's too much trouble or time for you. And thank you again!
