### ISSUE TITLE
Won't Complete

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/displaying-has-many-through-rails#6]
Lab will not mark as complete.

When I started the lab, there was a repo to fork, which I did.  Now lab has correctly converted to a readme.  I have two green lights, but lab does not register as complete.

**Comment by AnnJohn** [comment]
Hi @jakebrady5 this too we changed to a readme since there were no specs to actually make this lab. For the green lights, you can use the Ask a Question tool or email the Learn team. Thanks!
